apiVersion: skaffold/v3
kind: Config
metadata:
  name: microservices-ticketing
manifests:
      rawYaml:
       - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: mehradi/microservices-ticketing-auth:0.0.1
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .   

